# This is a basic workflow to help you get started with Actions

name: hola-mundo

# Controls when the workflow will run
on: [ push ]
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hola-mundo:
    # The type of RUNNER that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3
        
      - name: Hola mundo
        run: echo ¡Hola Mundo desde ${{steps.ip.outputs.ipv4}}!
      
      - name: Hola node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18
          
      - name: run node
        run: node index.js

      
