# This is a basic workflow to help you get started with Actions

name: triggers

# Controls when the workflow will run
on: 
  push:
    branches:
      - main
      - aprendiendo-github-actions
      
  pull_request:
    types: [opened, reopened]
    
  issues:
    types: [opened, edited, closed]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  triggers:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Hola node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
          
      - name: run node
        run: node index.js

      - name: Run on push, pull request, or issue
        run: echo "This workflow ran due to a push, pull request, or issue event."

      
